<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Enrollment;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        if (! app()->environment('local', 'testing')) {
            throw new \RuntimeException('Demo seeding is restricted to local and testing environments.');
        }
        $instructor = User::firstOrCreate(['email' => 'instructor@example.test'], ['name' => 'Cynthia Owolabi', 'password' => Hash::make('fieldnotes-demo-2026')]);
        $instructor->forceFill(['is_instructor' => true])->save();
        $learner = User::firstOrCreate(['email' => 'learner@example.test'], ['name' => 'Alex Morgan', 'password' => Hash::make('fieldnotes-demo-2026')]);
        User::firstOrCreate(['email' => 'maya@example.test'], ['name' => 'Maya Ellis', 'password' => Hash::make('fieldnotes-demo-2026')]);
        $catalog = [
            ['title' => 'The art of noticing', 'slug' => 'the-art-of-noticing', 'category' => 'Creative thinking', 'description' => 'Slow down, look closer, and turn everyday observations into fresh ideas.', 'lessons' => [
                ['A fresh pair of eyes', 8, "## Attention is a skill\nWe often walk through familiar places on autopilot. Noticing is the practice of interrupting that habit: choosing one small thing and paying attention to it without immediately deciding what it means.\n\nA designer might notice that a door handle looks like it should be pulled, even though the door opens with a push. A writer might notice that a quiet room is full of small sounds. Both start with observation, not a solution.\n\n## Try a five-minute field study\nChoose a familiar object: a cup, a notebook, or a chair. Write down ten things you can directly observe. Include its shape, texture, position, and signs of use. Avoid judgments like 'beautiful' or 'badly designed' for now.\n\n> An observation describes what is there. An interpretation explains what you think it means.\n\nCompare 'The mug has a chipped rim' with 'Someone was careless with this mug.' The first is observable; the second is a story that may be wrong.\n\n## Take it with you\nBefore your next meeting, spend one minute noticing your surroundings. Keep one concrete observation in a notebook. The aim is not to be clever. It is to see what you normally miss.", 'Which statement is an observation rather than an interpretation?', ['The room feels neglected.', 'There are three unopened envelopes on the table.', 'The owner must be very busy.'], 1],
                ['Ask a better question', 9, "## Give curiosity somewhere to go\nAn observation is a starting point. A good question opens up possibilities without quietly deciding the answer in advance.\n\n'Why is this interface so confusing?' assumes confusion and blame. 'Where do people pause while using this interface?' invites evidence.\n\n## Open, then narrow\nBegin with questions that invite a range of answers: What happens here? What changes over time? Who experiences this differently? Then narrow your focus to something you can actually investigate.\n\nFor the chipped mug, you could ask: Where does the rim touch other objects during washing? This is more useful than guessing who broke it.\n\n## A small practice\nTake yesterday's observation and write three questions about it. Circle the question that you could explore in ten minutes without buying anything or asking for special access.\n\n> Curiosity becomes useful when you can name your next small action.\n\nKeep the other questions. They may be worth returning to later.", 'Which question best invites evidence?', ['Why do users hate this page?', 'Why did the designer make a mistake?', 'At which step do users stop?'], 2],
                ['Build a noticing habit', 7, "## Make the practice easy to return to\nHabits become easier when the action is small and connected to something you already do. You do not need a special journal or an uninterrupted hour.\n\nAfter your morning drink, write one observation and one question. That is enough. Use the same notebook or file so that finding your notes does not become another task.\n\n## Review, do not just collect\nOnce a week, read your observations. Underline recurring themes. Perhaps you keep noticing how people wait, where sunlight falls, or which instructions people overlook. A theme can become a drawing, an experiment, or a useful change.\n\n## Your first experiment\nChoose one theme and make a small, reversible change. If visitors miss a sign, try a clearer position and observe what changes. Record the result even if nothing improves.\n\n> A field note is a record of learning, not proof that your first idea was right.\n\nYou have finished the course when you can move from observation to question to a small experiment. Keep the loop going.", 'What makes a sustainable noticing practice?', ['One small observation attached to an existing routine.', 'Waiting for a completely free afternoon.', 'Only writing down impressive ideas.'], 0],
            ]],
            ['title' => 'Write with clarity', 'slug' => 'write-with-clarity', 'category' => 'Communication', 'description' => 'Find the point, cut the noise, and make your next message easier to understand.', 'lessons' => [
                ['Start with the reader', 8, "## Give your message a job\nBefore writing, name the person who will read your message and what they need to do after reading it. A status update, a request for help, and a proposal have different jobs.\n\nA reader needs the conclusion before the history. 'We need a decision on the venue by Friday' is a useful opening. Five paragraphs of planning history make that decision harder to find.\n\n## Try it\nChoose a message you recently sent. Write its purpose in one sentence: 'After reading this, the reader should…' Remove anything that does not help that purpose.\n\n## Leave enough context\nClarity does not mean deleting every detail. Keep the facts your reader needs to act: the decision, the deadline, and the consequence of delay.", 'What should you clarify before drafting?', ['How many paragraphs to write.', 'What the reader needs to know or do.', 'Which impressive words to include.'], 1],
                ['Trade abstractions for details', 10, "## Show what you mean\nAbstract phrases ask the reader to do the work. 'Improve communication' could mean many things. 'Send a three-line handover before the next shift' gives someone an action.\n\nUse concrete nouns and active verbs where possible. Instead of 'The implementation of changes was undertaken', write 'The team updated the form.'\n\n## Keep useful precision\nNumbers, examples, and specific conditions help when they are relevant and supported. Do not invent a measurement just to sound precise.\n\n## Practice\nRewrite this sentence: 'We should optimize the onboarding experience.' Name one change, who will make it, and how you will check whether it helped.", 'Which revision gives a concrete next action?', ['Enhance stakeholder alignment.', 'Drive improved onboarding outcomes.', 'Ask three new users to try the signup form and record where they pause.'], 2],
                ['Edit for the next action', 7, "## Read your draft like a busy person\nLook only at the first sentence of each paragraph. Can you understand the message? If not, move the main point closer to the beginning.\n\n## Three editing passes\nFirst, check the purpose: does the message answer the reader's real question? Second, check the sequence: does each sentence prepare for the next? Third, check the words: can a shorter, familiar word say the same thing?\n\n## End where the reader can act\nA useful ending names the next step. 'Please choose option A or B by Thursday' is easier to act on than 'Please advise'. If no action is needed, say so.\n\n> An edit succeeds when the reader spends less effort finding the meaning.", 'Which ending makes the next step clearest?', ['Please choose A or B by Thursday.', 'Kindly do the needful.', 'We await further alignment.'], 0],
            ]],
            ['title' => 'Everyday systems thinking', 'slug' => 'everyday-systems-thinking', 'category' => 'Problem solving', 'description' => 'See the connections behind a problem and make changes that hold up over time.', 'lessons' => [
                ['Look beyond the event', 9, "## A problem has a setting\nWhen a queue grows, it is tempting to blame the person serving it. Systems thinking asks what conditions shape the result: arrival rates, available tools, interruptions, and the rules people follow.\n\nAn event is what happened today. A pattern is what keeps happening. A structure is what makes that pattern likely.\n\n## Map one small system\nChoose a familiar process, like getting ready for work. List the steps and dependencies. Which steps wait for another step? Where does an interruption spread?\n\nDo not try to map the entire world. Draw a boundary around the question you want to answer, then note what you have left outside it.", 'Which question looks beyond a single event?', ['Who can we blame for this morning?', 'What conditions make the delay happen repeatedly?', 'How can we hide the queue?'], 1],
                ['Follow the feedback', 10, "## Effects can become causes\nA feedback loop exists when the result of an action influences the next action. Practice can build confidence, which encourages more practice. That is a reinforcing loop.\n\nA thermostat behaves differently: when the room warms, heating reduces. That is a balancing loop, acting against a change.\n\n## Notice the delay\nFeedback is rarely immediate. If you water a plant every hour because it still looks dry, the delay in its response can lead you to overwater it.\n\nBefore reacting again, ask how long the system needs to show a result. Record when you made a change so you can compare like with like.", 'Why do delays matter when changing a system?', ['They mean feedback is useless.', 'They always prove the change failed.', 'Acting again too soon can overcorrect before the first change takes effect.'], 2],
                ['Choose a small intervention', 8, "## Change one thing you can learn from\nA useful intervention is small enough to reverse and clear enough to evaluate. Changing five things at once makes it harder to understand what mattered.\n\nFor a recurring meeting that runs late, try sharing the decision to be made before the meeting starts. Observe the duration and whether the decision is reached. Do not judge success using duration alone.\n\n## Watch for displaced problems\nAn improvement in one place can move the burden elsewhere. Faster customer intake may create a larger queue for the next team. Ask who experiences the downstream effects.\n\n## Close the loop\nState your expectation, make the change, wait for a reasonable interval, and compare the result. Keep, revise, or undo the change based on what you find.", 'What is a useful first intervention?', ['A small reversible change with a stated expectation and a way to observe results.', 'A complete redesign with no baseline.', 'Several simultaneous changes with no record.'], 0],
            ]],
        ];
        foreach ($catalog as $entry) {
            $lessons = $entry['lessons'];
            unset($entry['lessons']);
            $course = Course::firstOrCreate(['slug' => $entry['slug']], $entry + ['user_id' => $instructor->id, 'published' => true, 'level' => 'Beginner']);
            foreach ($lessons as $i => $lesson) {
                $course->lessons()->firstOrCreate(['position' => $i + 1], ['title' => $lesson[0], 'minutes' => $lesson[1], 'body' => $lesson[2], 'quiz' => ['question' => $lesson[3], 'options' => $lesson[4], 'correct' => $lesson[5]]]);
            }
        }
        Enrollment::firstOrCreate(['user_id' => $learner->id, 'course_id' => Course::where('slug', 'the-art-of-noticing')->firstOrFail()->id]);
    }
}
